# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: hello-world-cd

plugins:
  - serverless-offline

# exclude the code coverage files and circle ci files
package:
  exclude:
    - coverage/**
    - .circleci/**

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs10.x

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.helloWorld
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: hello-world
          method: get
          cors: true
